### ISSUE TITLE
OSSFileIO not compatible with aliyun-sdk-oss higher than 3.11.3

### ISSUE THREAD

**Issue by 769484623** [apache/iceberg#9934]
### Apache Iceberg version

1.4.3

### Query engine

Flink

### Please describe the bug 🐞

```java
import org.apache.hadoop.conf.Configuration;
import org.apache.iceberg.CatalogUtil;
import org.apache.iceberg.aliyun.AliyunProperties;
import org.apache.iceberg.io.FileIO;
import java.util.HashMap;
import java.util.Map;
public class Test {
    public static void main(String[] args) {
        Configuration hadoopConf = new Configuration();
        Map<String, String> hiveProperties = new HashMap<>();
        hiveProperties.put(AliyunProperties.CLIENT_ACCESS_KEY_ID, "AK");
        hiveProperties.put(AliyunProperties.CLIENT_ACCESS_KEY_SECRET, "SK");
        hiveProperties.put(AliyunProperties.OSS_ENDPOINT, "oss-cn-shenzhen.aliyuncs.com");
        FileIO io = CatalogUtil.loadFileIO("org.apache.iceberg.aliyun.oss.OSSFileIO", hiveProperties, hadoopConf);
        io.deleteFile("oss://xxx/filename.txt");
    }
}
```

above is the test code, throws

```
 Exception in thread "main" java.lang.NoSuchMethodError: com.aliyun.oss.OSS.deleteObject(Ljava/lang/String;Ljava/lang/String;)V
	at org.apache.iceberg.aliyun.oss.OSSFileIO.deleteFile(OSSFileIO.java:87)
	at com.dji.infra.data.dispatch.Test.main(Test.java:20)
```

after some debugging, found OSS interface changing from `void deleteObject(String, String)`  to `VoidResult deleteObject(String, String)` causes this issue.

for that reason, currently cannot work with aliyun-sdk-oss higher than 3.11.3.

any plans for adapting latest oss-sdk?

thanks

**Comment by 769484623** [comment]
besides, it would be great to add some docs about aliyun-oss, really hard to find useful info 🤣

**Comment by 769484623** [comment]
> Currently the version being used in Iceberg is
> 
> https://github.com/apache/iceberg/blob/b714978583f5ba32ec34396cb82b0a8f100bf837/gradle/libs.versions.toml#L24
> 
> 
> That means you'd have to make sure that your application uses the same version as Iceberg.
> I'm not sure who actively maintains the `OSSFileIO` but feel free to open a PR and upgrade the underlying version being used.

thanks nastra. 

as using the same version can make it work, i'll close this issue.
