### ISSUE TITLE
How to build iceberg on windows?

### ISSUE THREAD

**Issue by liuxiaocs7** [apache/iceberg#7101]
### Question

Hello everyone, I follow the [instruction](https://github.com/apache/iceberg#building) to build iceberg on windows, when i try to execute `./gradlew build`, it seems fails, result are as follows.

```shell
Gradle Test Executor 122 finished executing tests.

> Task :iceberg-nessie:test FAILED

236 tests completed, 11 failed, 26 skipped
Finished generating test XML results (0.005 secs) into: D:\Development\Code\iceberg\nessie\build\test-results\test
Generating HTML test report...
Finished generating test html results (0.011 secs) into: D:\Development\Code\iceberg\nessie\build\reports\tests\test

FAILURE: Build completed with 3 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':iceberg-hive-metastore:test'.
> There were failing tests. See the report at: file:///D:/Development/Code/iceberg/hive-metastore/build/reports/tests/test/index.html

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':iceberg-aliyun:test'.
> There were failing tests. See the report at: file:///D:/Development/Code/iceberg/aliyun/build/reports/tests/test/index.html

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

3: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':iceberg-nessie:test'.
> There were failing tests. See the report at: file:///D:/Development/Code/iceberg/nessie/build/reports/tests/test/index.html

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/8.0.2/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 3m 58s
273 actionable tasks: 254 executed, 19 up-to-date
Watched directory hierarchies: [D:\Development\Code\iceberg]
Stopped 15 worker daemon(s).G [3m 57s]
```

**Comment by nastra** [comment]
The Iceberg build doesn't officially support Windows, but you might try and run `./gradlew wrapper --gradle-version 8.0.2 --gradle-distribution-sha256-sum ff7bf6a86f09b9b2c40bb8f48b25fc19cf2b2664fd1d220cd7ab833ec758d0d7` locally. 
This will then produce a `gradlew.bat` for Windows. You could try and see how far you could get with this.

However, there are most likely a bunch of places in the build that rely on non-Windows behavior.

**Comment by liuxiaocs7** [comment]
> The Iceberg build doesn't officially support Windows. However, coud you maybe show why the tests are failing?

According to the logs, there are mainly three modules that fail, they are:
- iceberg-hive-metastore:test
- iceberg-aliyun:test
- iceberg-nessie:test

Hive metastore failed tests:
![image](https://user-images.githubusercontent.com/42756849/224959255-16e5d2a6-7921-491b-9fc4-b5fa2f2776f9.png)

some wrong stack are:

```
java.lang.NullPointerException
	at org.apache.iceberg.hive.HiveMetastoreTest.stopMetastore(HiveMetastoreTest.java:79)

java.lang.NoClassDefFoundError: Could not initialize class org.apache.iceberg.hive.TestHiveMetastore
	at org.apache.iceberg.hive.HiveMetastoreTest.startMetastore(HiveMetastoreTest.java:50)
	at org.apache.iceberg.hive.HiveMetastoreTest.startMetastore(HiveMetastoreTest.java:46)

java.lang.NoClassDefFoundError: Could not initialize class org.apache.iceberg.hive.TestHiveMetastore
	at org.apache.iceberg.hive.HiveMetastoreTest.startMetastore(HiveMetastoreTest.java:50)
	at org.apache.iceberg.hive.TestHiveCommitLocks.startMetastore(TestHiveCommitLocks.java:87)
```

---

Aliyun failed tests:
![image](https://user-images.githubusercontent.com/42756849/224959347-0432e356-fd1d-4061-a755-114f0af5d062.png)


log:

```shell
com.aliyun.oss.OSSException: The bucket you tried to delete is not empty. 
[ErrorCode]: BucketNotEmpty
[RequestId]: null
[HostId]: null
[ResponseError]:
```

---

Nessie failed tests:
![image](https://user-images.githubusercontent.com/42756849/224959456-0b818d21-943a-42f0-9632-d6a401e22d46.png)


```shell
java.nio.file.InvalidPathException: Illegal character [:] in path at index 4: ///C:/Users/LIUXIA~1/AppData/Local/Temp/junit1820669570277894084//test-ns/table1_4da0d827-b94c-4073-900d-070e34024f79/data/initial-data.avro
	at sun.nio.fs.WindowsPathParser.nextSlash(WindowsPathParser.java:212)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:111)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
```

**Comment by liuxiaocs7** [comment]
Windows is pretty much not supported by the Iceberg build now,  I try to build on WSL2(Ubuntu 22.04), it works for me.
