### PR TITLE
Build: Integrate Scalafix to auto-fix unused Scala imports

### PR DESCRIPTION
**Pull request by jackylee-ch**
Integrate Scalafix with the RemoveUnused rule to automatically fix unused Scala imports via `./gradlew scalafix`.
Fix https://github.com/apache/iceberg/issues/14342

### CODE REVIEW

File: site/docs/contribute.md [hunk 1]
```diff
@@ -303,6 +304,12 @@ In order to automatically fix Java code style issues, please use `./gradlew spot
 since that version is compatible with JDK 8. When formatting the code in the IDE, there is a slight chance that it will produce slightly different results. In such a case please run `./gradlew spotlessApply`
 as CI will check the style against **google-java-format** 1.7.
 
+For Scala code, unused imports are treated as compilation errors. To automatically remove unused imports, run [Scalafix](https://scalacenter.github.io/scalafix/):
+
+```bash
+./gradlew scalafix -DsparkVersions=4.0 -DscalaVersion=2.13
```
Comment (huaxingao) [inline site/docs/contribute.md:310]: Does this also work with Spark 3.5 scala 2.12?

Comment (jackylee-ch) [reply site/docs/contribute.md:310]: Yes, it works.

**Comment by huaxingao** [comment]
LGTM from my side. Any other reviewers interested in taking a look? Maybe @RussellSpitzer ?

**Comment by RussellSpitzer** [comment]
I'm not familiar with this tool, I would just double check we can't already support this with the existing plugins we have. If not then I don't have a problem. I can review more seriously when I get to a computer since I'll need to learn more about this tool

**Comment by jackylee-ch** [comment]
remind @RussellSpitzer, PTAL

**Comment by RussellSpitzer** [comment]
@jackylee-ch Did you have a response for my comment?

**Comment by jackylee-ch** [comment]
> @jackylee-ch Did you have a response for my comment?

Oh, sorry, I misunderstood. Just as I replied in the PR of [Build: Apply spotless for scala code](https://github.com/apache/iceberg/pull/8023#issuecomment-3399820568), there's currently no other solution to the unused import problem.
image

File: baseline.gradle [hunk 2]
```diff
@@ -187,6 +187,21 @@ subprojects {
...
+    scalafix {
+      configFile = file("${rootDir}/.baseline/scala/.scalafix.conf")
+      semanticdb {
+        autoConfigure = true
+      }
+    }
+
+    // When running scalafix, downgrade unused import errors to warnings so that
+    // compilation succeeds and SemanticDB is produced for Scalafix to process.
+    boolean scalafixRun = gradle.startParameter.taskNames.any {
```
Comment (RussellSpitzer) [inline baseline.gradle:201]: This really feels like a bug in the cosmic-silence plugin. It should be automatically be downgrading the tasks on it's own.

Comment (jackylee-ch) [reply baseline.gradle:201]: Its working principle is to handle the issue only after a Scala compile warning occurs, since it doesn't perform the unused check itself.

Comment (jackylee-ch) [reply baseline.gradle:201]: In fact, introducing Scalafix is ​​a bit heavy, but we [lack this component](https://github.com/apache/iceberg/pull/14344#issuecomment-3410567850). 
Alternatively, do you think we can maintain the current state and let users handle this code style issue themselves when they receive compilation failures related to unused imports?
If so, the PR and the issue can be closed now.

Comment (RussellSpitzer) [reply baseline.gradle:201]: I think we are better off just not adding anything to the build, I've grown very paranoid of adding things to the build with all the supply chain attacks lately and even though I think this would be relatively safe, I don't think we really gain that much by giving folks an auto fix command. We aren't really a scala project so the benefits here feel very low compared to adding complexity to the build and a new plugin.

Comment (jackylee-ch) [reply baseline.gradle:201]: OK, would close current PR and Issue. Thanks for your clarify.
