### PR TITLE
Document Parquet version compatibility issue between Spark and Iceberg

### PR DESCRIPTION
**Pull request by huaxingao**
Document the Parquet version compatibility issue between Spark and Iceberg in this discussion thread: https://www.mail-archive.com/dev%40iceberg.apache.org/msg11782.html?

### CODE REVIEW

**Comment by huaxingao** [comment]
cc @jbonofre @manuzhang @nastra

**Comment by pan3793** [comment]
IIRC, Iceberg uses its own shaded Parquet classes. How does the NoSuchMethodError happen?

**Comment by pan3793** [comment]
BTW, in practice, `spark.[driver|executor].userClassPathFirst=true` should be highly discouraged as it usually brings more problems than it solves ...

**Comment by manuzhang** [comment]
> IIRC, Iceberg uses its own shaded Parquet classes. How does the NoSuchMethodError happen?

@jbonofre Can you share more of your failed tests here?

File: docs/docs/spark-configuration.md [hunk 1]
```diff
@@ -197,6 +197,14 @@ val spark = SparkSession.builder()
 | spark.sql.iceberg.merge-schema                         | false                                                          | Enables modifying the table schema to match the write schema. Only adds columns missing columns                                 |
 | spark.sql.iceberg.report-column-stats                  | true                                                           | Report Puffin Table Statistics if available to Spark's Cost Based Optimizer. CBO must be enabled for this to be effective       |
 
+### Classpath order and Parquet version compatibility
+
+Spark distributions may bundle a different Parquet version than Iceberg’s Spark runtime. For example, Spark 4.0.x uses Parquet 1.15.2 while Iceberg 1.10.x can use Parquet 1.16.0 for features like Variant/Geometry. With the default classpath order, Spark’s older Parquet may be picked up first and can cause NoSuchMethodError when Iceberg code invokes newer Parquet APIs.
```
Comment (singhpk234) [inline docs/docs/spark-configuration.md:202]: is 1.10.1 release notes a better place to document this ? 

orthogonally can we not shade it and track it as a fix for 1.10.x, to avoid user configuring these config as the same can be true for other engine ?

**Comment by jbonofre** [comment]
For the context, doing query in Spark SQL works fine.

I got `java.lang.NoSuchMethodError: 'org.apache.parquet.schema.LogicalTypeAnnotation$VariantLogicalTypeAnnotation org.apache.parquet.schema.LogicalTypeAnnotation.variantType(byte)` as soon as I'm doing table maintenance.

For instance, a simple:

```
var actions = SparkActions.get(sparkSession);
actions.rewriteDataFiles(table)
                      .option(
                          "target-file-size-bytes",
                          Long.toString(configuration.rewriteDataFile().targetFileSize())).execute();
```

reproduce the issue (with Spark 4).

NB: It works fine with Spark 3.5, not with Spark 4 (and the corresponding Iceberg extension).

**Comment by jbonofre** [comment]
By the way, it should work if using `iceberg-spark-runtime` artifact (as this one shades parquet). I gonna try it.

**Comment by pan3793** [comment]
@jbonofre, I think the end-user is always supposed to use runtime jars for compute engine integration.
